### ISSUE TITLE
Adapt to ongoing changes in r4ss

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/nwfscDiag#18]
Some {r4ss} functions used by the nwfscDiag package are being changed in Pull Request https://github.com/r4ss/r4ss/pull/722 with further changes proposed in issue https://github.com/r4ss/r4ss/issues/723. 

The changes includes renaming functions and also revising the arguments for those that run profiles, retrospectives, and jitters.

This is both a heads up that changes will be needed here once the {r4ss} package changes and also an opportunity for @chantelwetzel-noaa and anyone else interested to give input on the r4ss changes while they are still in process.

**Comment by chantelwetzel-noaa** [comment]
Thanks @iantaylor-NOAA.  Trust me, your proposed changes have already given me heartburn for this package.  However, everything looks reasonable and as long as we align timing on the changes between r4ss and this package we should be okay.

**Comment by k-doering-NOAA** [comment]
@chantelwetzel-noaa, the nice thing is that the gha will help you catch them faster :)

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa no need for heartburn 😞 it will be okay.

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa, let me know if you'd like me to attempt the changes to nwfscDiags required by the recent changes in r4ss?

**Comment by chantelwetzel-noaa** [comment]
@iantaylor-NOAA Thanks but no need for you to attempt these changes. I plan on working on next week as a chance to understand all the new changes in r4ss. I am sure I will have questions for you when that time comes.
