### ISSUE TITLE
naming and input conventions for profiles

### ISSUE THREAD

**Issue by owenhamel** [pfmc-assessments/nwfscDiag#2]
man/get_settings_profile.Rd:
The descriptions here may be accurate, but it is far from intuitive. It is not immediately clear that “relative” is simply “additive” to the base value, nor that “multiplier” is actual multiplying by either one minus or one plus the value given, dependent if it is low or high (note that alternative interpretations are not needed for the “real” or “relative” cases). I would suggest using “additive” and “actual” (since all the numbers you are using are real, as opposed to imaginary). I would also suggest that if you are going to use “multiplier”, have the input be the actual multipliers (e.g. 0.6, 1.4). That would be the most intuitive approach. Otherwise use “relative multiplier” (or perhaps you can improve upon that) to describe a proportional decrease or increase, in which the inputs would indicate the direction (e.g. -0.4, 0.4). 
In addition, in the description, x% is used to refer to numbers that are proportions rather than percents.

**Comment by chantelwetzel-noaa** [comment]
Details have been added to the function that provides examples for the user for each type of setting.
