### ISSUE TITLE
Control the decimals in plot legend

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/nwfscDiag#20]
https://github.com/pfmc-assessments/nwfscDiag/blob/582820cf21cab0506b28d99a9770ceb7c7fbef9e/R/profile_plot.R#L197

@kellijohnson-NOAA Can you help me to understand how to modify this line to control rounding in a dynamic fashion. My test is for a natural mortality profile were I want to specifically have 3 decimals. Currently, it is rounding down to 2 decimals which does not reflect the used step size. Conversely, I don't want the default to be 3 decimals were it would not be appropriate (e.g., steepness maybe).

**Comment by chantelwetzel-noaa** [comment]
Here is an example figure of the issue below where the base parameter was 0.108 but is being rounded up to 0.11 with two decimals since the profile is run across the vec R object:  

0.080 0.090 0.100 0.108 0.110 0.120 0.130 0.140 0.150

If we are able to dynamically determine the max non-zero decimal in the "vec" R object and then set that as the number of decimals to print this should work fine as a solution.

![NatM_p_1_Fem_GP_1_trajectories_compare3_Bratio](https://user-images.githubusercontent.com/6172110/197072878-2097de1b-4a5a-486e-a02f-d324d2324ffe.png)

**Comment by brianlangseth-NOAA** [comment]
@chantelwetzel-noaa Not sure if you already have the logic down but this could work: round the base number to match the number of decimals in "vec", if that rounded number equals any of the numbers in "vec" then round the base to a number with more decimals.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa for the detailed issue and @brianlangseth-NOAA for the suggestion. The trouble with this code that I wrote in 4864c5426695e796655f3ba4a832f596f8ebcea4 is that it is trying to do too many things, and thus, it is not interpretable. I propose that we
1. Write a helper function called `pretty_decimals()` that can determine the appropriate number of decimals to include given a set of real numbers.
2. Use the helper function on `x`.
3. Then lastly paste the parameter name, results from (2), and the qualifier of `(base)` for the appropriate entry.

I will open a pull request shortly.

**Comment by iantaylor-NOAA** [comment]
Fix seems really valuable. Good job @kellijohnson-NOAA, @chantelwetzel-noaa, and @brianlangseth-NOAA.

Not to add more complexity, but what about the case where the base model is fixed at a round number that's already included in the profile vector? I can't follow the logic in the function well enough to figure out whether that case would lead to this error:
```
> pretty_decimal(c(0.08, 0.09, 0.10, 0.11, 0.11, 0.12, 0.13, 0.14, 0.15))
Error in pretty_decimal(c(0.08, 0.09, 0.1, 0.11, 0.11, 0.12, 0.13, 0.14,  : 
  !any(duplicated(x)) is not TRUE
```

**Comment by chantelwetzel-noaa** [comment]
Good question. I did not run this type of test on the new function. However, I think wouldn't recommend people included the base model parameter and in the the vector of values profiled across (e.g., h = 0.70 and profiling across seq(0.25, 1, 0.05)). I think adding some internal logic to check and correct this would be better than modifying the pretty_decimal function.  I will look to see what the code currently does in this situation and modify if needed.

**Comment by kellijohnson-NOAA** [comment]
One would hope that you don't have that value in your vector 😆

**Comment by iantaylor-NOAA** [comment]
Thanks for digging into it @chantelwetzel-noaa.
Yes, @kellijohnson-NOAA, one would hope, but it's easy to imagine in the current configuration that you specify the profile details once (e.g. via https://github.com/pfmc-assessments/lingcod/blob/main/inst/extdata/diagpars.csv) and rerun nwfscDiags for a variety of model configurations. But if `profile_wrapper()` can just pull out the base model value from the vector (if it exists there) before running the profile, that would save time and avoid the error.

**Comment by chantelwetzel-noaa** [comment]
Past me is sometimes smart and clever. I confirmed that there is existing logic in the profile_wrapper function that checks to see if the base parameter value is included in the vector to profile across and removes the duplicate value appropriately.

**Comment by iantaylor-NOAA** [comment]
Nice job past and current @chantelwetzel-noaa!
