### ISSUE TITLE
let user see the profile vector before running r4ss::profile()?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/nwfscDiag#28]
Another suggestion outside the scope of #24.

I think the calculation of profile vectors described in detail in 
https://github.com/pfmc-assessments/nwfscDiag/blob/main/R/get_settings_profile.R#L7-L15
is really brilliant for providing a range that works for lots of models.

However, I would find it helpful to see what `vec` is before waiting a few hours for the profiles to run and looking at the resulting figures and tables. This could be combined with #25,  such that if you could call `profile_wrapper()` without running the models or making the plots, you could see if the profile vectors calculated from the inputs on a multiplier or relative scale look reasonable.

Also very low priority.

**Comment by chantelwetzel-noaa** [comment]
A function that reports the profile information has been added to `get_settings()`.
