### ISSUE TITLE
Plotting Piner and parameter plots

### ISSUE THREAD

**Issue by shcaba** [pfmc-assessments/nwfscDiag#34]
Using the new r4ss, I did a likelihood profile on lnR0.
The biomass and depletion plots show up, but the Piner and parameter plots are blank files.
If I debug and walk through the code, it does properly make those plots, but for some reason it does not save them properly.
I am not sure if this is just my issue or if others are not getting all plots saved properly.

**Comment by kellijohnson-NOAA** [comment]
@shcaba what do you mean by "new" r4ss. Which version are you using?

**Comment by shcaba** [comment]
I believe r4ss updated some things, like referencing the ss executable as
ss3.
Those two particular plots are just creating blank files for me now (they
had been working before I updated r4ss).
Again, they plot correctly when I walk through the profile function code,
they just don't save correctly.
