### ISSUE TITLE
Propose to remove code that creates mohnsrho.tex file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/nwfscDiag#36]
The code below leads to the creation of mohnsrho.tex, which can be brought into an assessment document without editing. This table is not listed in the TOR as required. I am proposing that we remove the code that creates it and the documentation suggesting that a .tex file is created and encourage users to put in the figure. If we keep the table, I need to figure out why it is not automatically tagged like the other tables are. Currently, each cell has to be manually tagged. It is small so it is not a big deal and is not why I am proposing that we remove the code. Please give a 👎 or 👍 by clicking on the smiley face 😃 below this comment.
https://github.com/pfmc-assessments/nwfscDiag/blob/c0cb2d5b169e07d12f38416cf0e2b13277a6c973/R/retro_wrapper.R#L205-L238

**Comment by chantelwetzel-noaa** [comment]
I am fine removing this code, especially since we will still be producing the csv file that contains the quantities.  👍

**Comment by brianlangseth-NOAA** [comment]
I also support removing this code. As @chantelwetzel-noaa mentioned the CSV file produces these outputs. I haven't used the table in the report but rather one of the values into the text of the assessment itself.

**Comment by chantelwetzel-noaa** [comment]
This table has been removed.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa for following through with this 😃!
